## Build an AItransDTP format image with server and client from the src code
## This dockerfile build server and client from `examples/` and put them in their corresponding position
## in `aitrans-server` folder in aitrans_image_base
## ** Prerequisites
## This dockerfile uses [rust chef] to accelerate the building process
FROM simonkorl0228/aitrans_build:buster AS chef
# dependencies
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN echo "[source.crates-io]\n\
    replace-with = 'tuna'\n\n\
    [source.tuna]\n\
    registry = \"https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git\"" > $CARGO_HOME/config && \
    apt-get update && apt-get install --no-install-recommends -y uthash-dev
RUN cargo install cargo-chef 
WORKDIR /build
# planner
FROM chef AS planner
COPY ./deps/DTP/benches ./benches
COPY ./deps/DTP/deps ./deps
COPY ./deps/DTP/examples ./examples
COPY ./deps/DTP/src ./src
COPY ./deps/DTP/include ./include
COPY ./deps/DTP/Cargo.toml ./Cargo.toml
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
WORKDIR /build
COPY --from=planner /build/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
# build app
COPY ./deps/DTP/benches ./benches
COPY ./deps/DTP/deps ./deps
COPY ./deps/DTP/examples ./examples
COPY ./deps/DTP/src ./src
COPY ./deps/DTP/include ./include
COPY ./deps/DTP/Cargo.toml ./Cargo.toml
WORKDIR /build/builder
COPY ./c_interface .
RUN make

FROM simonkorl0228/aitrans_image_base:buster
COPY --from=builder \
    /build/builder/server /home/aitrans-server/bin/server
COPY --from=builder \
    /build/builder/client /home/aitrans-server/client
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN apt update && apt install --no-install-recommends -y tcpdump vim ntp
WORKDIR /home/aitrans-server

