FROM sc_base_cinterface_w88:latest AS chef
# dependencies
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN echo "[source.crates-io]\n\
    replace-with = 'tuna'\n\n\
    [source.tuna]\n\
    registry = \"https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git\"" > $CARGO_HOME/config && \
    apt-get update && apt-get install --no-install-recommends -y uthash-dev
RUN cargo install cargo-chef 
WORKDIR /build
# planner
FROM chef AS planner
COPY ./benches ./benches
COPY ./deps ./deps
COPY ./examples ./examples
COPY ./src ./src
COPY ./include ./include
COPY ./Cargo.toml ./Cargo.toml
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
WORKDIR /build
COPY --from=planner /build/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
# build app
COPY ./benches ./benches
COPY ./deps ./deps
COPY ./examples ./examples
COPY ./src ./src
COPY ./include ./include
COPY ./Cargo.toml ./Cargo.toml
WORKDIR /build/builder
RUN make

FROM simonkorl0228/aitrans_image_base:buster
COPY --from=builder \
    /build/builder/server /home/aitrans-server/bin/server
COPY --from=builder \
    /build/builder/client /home/aitrans-server/client
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN apt update && apt install --no-install-recommends -y tcpdump vim ntp
WORKDIR /home/aitrans-server

